Created a template logic for each install script. Added more package scripts

diff --git a/packages/discord b/packages/discord
--- a/packages/discord
+++ b/packages/discord
@@ -1,2 +1,33 @@
 #!/bin/bash
-./_install_package discord snap
+PACKAGE_NAME="discord"
+
+# Installation function
+function install {
+	snap install $PACKAGE_NAME
+}
+
+# Checks if pacakge is installed and aborts if already exists.
+function check_package_status {
+	if $UTIL/check_installation $PACKAGE_NAME; then
+		echo "Already installed: $PACKAGE_NAME"
+		exit 0
+	else
+		echo "Installing: $PACKAGE_NAME"
+	fi
+}
+
+# Check if installation was successful, if not it aborts.
+function test_installation {
+	if $UTIL/check_installation $PACKAGE_NAME; then
+		echo "Installation successful: $PACKAGE_NAME"
+		exit 0
+	else
+		exit 1
+		echo "Installation failed: $PACKAGE_NAME"
+	fi
+}
+
+# Execution
+check_package_status	# Check if installed
+install			# Install package if missing
+test_installation	# Test if installation was successful
